#!/usr/bin/env bash
# Add instructor's SSH public key to the server for non-interactive access

USER="d92e296964c9"
HOST="d92e296964c9.d33531d3.alu-cod.online"
KEY="$HOME/.ssh/school"  # Your private key created in 1-create_ssh_key_pair
PUB_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNdtrNGtTXe5Tp1EJQop8mOSAuRGLjJ6DW4PqX4wId/Kawz35ESampIqHSOTJmbQ8UlxdJuk0gAXKk3Ncle4safGYqM/VeDK3LN5iAJxf4kcaxNtS3eVxWBE5iF3FbIjOqwxw5Lf5sRa5yXxA8HfWidhbIG5TqKL922hPgsCGABIrXRlfZYeC0FEuPWdr6smOElSVvIXthRWp9cr685KdCI+COxlj1RdVsvIo+zunmLACF9PYdjB2s96Fn0ocD3c5SGLvDOFCyvDojSAOyE70ebIElnskKsDTGwfT4P6jh9OBzTyQEIS2jOaE5RQq4IB4DsMhvbjDSQrP0MdCLgwkN"

# Connect to the server and append the public key if it does not exist
ssh -i "$KEY" "$USER@$HOST" "\
mkdir -p ~/.ssh && chmod 700 ~/.ssh && \
grep -qxF '$PUB_KEY' ~/.ssh/authorized_keys || echo '$PUB_KEY' >> ~/.ssh/authorized_keys && \
chmod 600 ~/.ssh/authorized_keys"