#!/usr/bin/env bash
# Configures nginx with a custom HTTP response header X-Served-By

apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Add custom header with the server's hostname
sed -i '/server_name _;/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Add 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _;/a \\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Add redirect
sed -i '/server_name _;/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
