#!/usr/bin/env bash
# Installs and configures HAProxy to distribute traffic to web-01 and web-02 using roundrobin

# Update package list and install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 6970-web-01 44.203.97.109:80 check
    server 6970-web-02 35.171.8.246:80 check
EOF

# Restart HAProxy to apply configuration
sudo service haproxy restart