#!/usr/bin/env bash
# Configures an Ubuntu machine to install and configure Nginx

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
sudo service nginx restart